[package]
name = "gmt_dos-clients_m1-ctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
center = { version = "0.1.1", package = "gmt_m1-ctrl_center-actuators" }
hardpoints-dynamics = { version = "0.1.1", package = "gmt_m1-ctrl_hardpoints-dynamics" }
outer = { version = "0.1.1", package = "gmt_m1-ctrl_outer-actuators" }
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_fem.workspace = true
nalgebra.workspace = true
gmt-fem.workspace = true
anyhow.workspace = true
log.workspace = true

[dev-dependencies]
matio-rs = { workspace = true, features = ["nalgebra"] }
tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_mount = { workspace = true, features = ["s8000d002ze30"] }
gmt_dos-clients_m1-ctrl.workspace = true
gmt_dos-clients_fem.workspace = true
gmt_dos-clients_arrow.workspace = true
anyhow.workspace = true
skyangle.workspace = true
gmt-fem.workspace = true
lom = { version = "1.1.0", package = "gmt-lom", features = ["main"] }
