[package]
name = "gmt_dos-clients_m2-ctrl"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS M2 Control Client"
documentation = "https://docs.rs/gmt_dos-clients_m2-ctrl"
readme = "../README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_m2-ctrl_asm_preshape-filter = "0.1.0"
gmt_m2-ctrl_asm_pid-damping = "0.1.0"
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_fem = { workspace = true, features = ["asm"] }
gmt-fem.workspace = true
rayon.workspace = true
nalgebra = { workspace = true, features = ["serde", "serde-serialize"] }
log.workspace = true
anyhow.workspace = true
matio-rs.workspace = true
thiserror.workspace = true
bincode = "1.3.3"
serde = { version = "1.0.152", features = ["derive"] }
paste = "1.0.12"

[dev-dependencies]
matio-rs = { workspace = true, features = ["nalgebra"] }
tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
nanorand.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_mount = { workspace = true, features = ["s8000d002ze30"] }
gmt_dos-clients_m1-ctrl.workspace = true
gmt_dos-clients_fem.workspace = true
gmt_dos-clients_arrow.workspace = true
anyhow.workspace = true
skyangle.workspace = true
gmt-fem.workspace = true
lom = { version = "1.1.0", package = "gmt-lom", features = ["main"] }
