[package]
name = "ngao"
version = "0.1.0"
edition = "2021"
description = "GMT Natural Guide Star Adaptive Optics"

[dependencies]
crseo.workspace = true
gmt_dos-actors.workspace = true
gmt_dos-clients = { workspace = true, features = ["clients"] }
gmt_dos-clients_io.workspace = true
gmt_dos-clients_crseo.workspace = true
gmt_dos-clients_arrow.workspace = true
gmt_dos-clients_m2-ctrl = { workspace = true, features = ["serde"] }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
env_logger.workspace = true
complot = { version = "0.3.3", optional = true }
num-traits = "0.2.15"
gmt_ngao_temporal_ctrl = { git = "https://github.com/rconan/gmt-m2-ctrl.git", branch = "master" }
gmt_dos-clients_domeseeing.workspace = true
thiserror.workspace = true
