[package]
name = "gmt_dos-clients_crseo"
version = "3.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS CRSEO Client"
documentation = "https://docs.rs/gmt_dos-clients_crseo"
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
interface.workspace = true
gmt_dos-clients_io.workspace = true
gmt_dos-clients_domeseeing.workspace = true
log.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
crseo.workspace = true
serde = { version = "1.0.152", features = ["derive"] }
anyhow.workspace = true
toml = "0.7.4"

[dev-dependencies]
gmt_dos-clients_arrow.workspace = true
linya = "0.3.0"
skyangle = "0.1.2"
tokio = "1.21.1"
