[package]
name = "gmt-fem-code-builder"
version = "2.2.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT FEM Code Builder"
documentation = "https://docs.rs/gmt-fem-code-builder"
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
apache-arrow.workspace = true
parquet.workspace = true
thiserror.workspace = true
zip.workspace = true
bytes.workspace = true
