[package]
name = "gmt_dos-clients_windloads"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "GMT DOS Windloads Client"
documentation = "https://docs.rs/gmt_dos-clients_windloads"
readme = "../README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
gmt_dos-actors.workspace = true
gmt_dos-clients = { workspace = true, features = ["interface"] }
log.workspace = true
thiserror = { workspace = true }
parse-monitors = "0.1.1"
geotrans = "0.2.2"
gmt-fem = { workspace = true }
gmt_dos-clients_io = { workspace = true }
